facturas/config/routes.rb
Rails.application.routes.draw do
  
  resources :invoices do
    resources :items
  end
  
  root 'invoices#index'
end

facturas/app/models/invoice.rb
class Invoice < ActiveRecord::Base
    has_many :items
end

facturas/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
end

facturas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

facturas/app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @items = @invoice.items
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:razon, :fecha, :nombre)
    end
end

facturas/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @invoice = Invoice.find(params[:invoice_id])
    @item = Item.new
    @item.invoice_id = @invoice.id
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.invoice_id = params[:invoice_id]

    respond_to do |format|
      if @item.save
        format.html { redirect_to invoice_path(params[:invoice_id]), notice: 'Item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:descripcion, :precio, :cantidad, :invoice_id)
    end
end

facturas/app/helpers/application_helper.rb
module ApplicationHelper
end

facturas/app/helpers/invoices_helper.rb
module InvoicesHelper
end

facturas/app/helpers/items_helper.rb
module ItemsHelper
end

facturas/app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :razon %>
    <%= f.input :fecha %>
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

facturas/app/views/invoices/_items.html.erb
<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th>Invoice</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.descripcion %></td>
        <td><%= item.precio %></td>
        <td><%= item.cantidad %></td>
        <td><%= link_to 'Edit', edit_invoice_item_path(@invoice,item) %></td>
        <td><%= link_to 'Destroy', invoice_items_path(@invoice,item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

facturas/app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

facturas/app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Facturas</h1>

<table>
  <thead>
    <tr>
      <th>Razón</th>
      <th>Fecha</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.razon %></td>
        <td><%= invoice.fecha %></td>
        <td><%= invoice.nombre %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

facturas/app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

facturas/app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Razon:</strong>
  <%= @invoice.razon %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @invoice.fecha %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @invoice.nombre %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>
<br/>
<%= link_to 'Crear detalle', new_invoice_item_path(@invoice) %>

<%= render 'items' %>

facturas/app/views/items/_form.html.erb
<%= simple_form_for [@invoice,@item] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :descripcion %>
    <%= f.input :precio %>
    <%= f.input :cantidad %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

facturas/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

facturas/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.descripcion %></td>
        <td><%= item.precio %></td>
        <td><%= item.cantidad %></td>
        <td><%= item.invoice %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

facturas/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', invoice_path(@invoice) %>

facturas/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @item.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @item.precio %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @item.cantidad %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @item.invoice %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

facturas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facturas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>